// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvuV-Tqv7lgirNJIQL7Ae8gIeyWDzLWEU',
    appId: '1:848746376569:android:6677bc03ca1d25c32553a8',
    messagingSenderId: '848746376569',
    projectId: 'todoapp-94a2d',
    databaseURL: 'https://todoapp-94a2d-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-94a2d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsdXv54YhucnP3ukNcAKTFNw3SpfRejgg',
    appId: '1:848746376569:ios:5b7011cf969ca7d62553a8',
    messagingSenderId: '848746376569',
    projectId: 'todoapp-94a2d',
    databaseURL: 'https://todoapp-94a2d-default-rtdb.firebaseio.com',
    storageBucket: 'todoapp-94a2d.firebasestorage.app',
    iosBundleId: 'com.example.notesapp',
  );
}
